// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication2.Persistence;

#nullable disable

namespace WebApplication2.Migrations
{
    [DbContext(typeof(CashierContext))]
    [Migration("20250418131417_App")]
    partial class App
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication2.Entities.Cashiers", b =>
                {
                    b.Property<Guid>("CashierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("CashierID");

                    b.Property<string>("CashierName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CashierName");

                    b.Property<int>("CashierPhoneNumber")
                        .HasColumnType("integer")
                        .HasColumnName("CashierPhoneNumber");

                    b.HasKey("CashierID");

                    b.ToTable("Cashiers");
                });
#pragma warning restore 612, 618
        }
    }
}
